version: '3'
services:
  mini-app-test:
    image: okcoinapi
    container_name: mini-app-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      MyDatabase__ConnectionString: "mongodb://root:root@mongodb-test:27017"
      MyDatabase__DatabaseName: "KingdomsDB"
      MyDatabase__RedisConnectionString: "redis-test:6379"
    ports: 
      - "9000:80"
    networks:
        - mini-app-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
        - mongodb-test
        - redis-test

  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data_test:/data/db
    ports:
      - "27018:27017"
    networks:
        - mini-app-test
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-test:
    image: redis:latest
    container_name: redis-test
    command: redis-server
    volumes:
      - redis_data_test:/data
    ports:
      - "6380:6379"
    networks:
        - mini-app-test
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data_test:
  redis_data_test:
networks:
  mini-app-test:
        driver: bridge