# Secret cho các thông tin nhạy cảm
apiVersion: v1
kind: Secret
metadata:
  name: okcoin-secrets
  namespace: minigame
type: Opaque
data:
  mongodb-connection-string: cm9vdDpyb290
  redis-connection-string: cmVkaXM6NjM3OQ==
#  uri => base64: =
# redis:6379 => base64: cmVkaXM6NjM3OQ==
---

# ConfigMap cho các giá trị cấu hình
apiVersion: v1
kind: ConfigMap
metadata:
  name: okcoin-config
  namespace: minigame
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  MyDatabase__DatabaseName: "OkCoinDB"

---

# Deployment cho okcoin-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okcoin-api
  namespace: minigame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okcoin-api
  template:
    metadata:
      labels:
        app: okcoin-api
    spec:
      containers:
        - name: okcoin-api
          image: metafi/ok-coin-api:0.1.0
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: okcoin-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: okcoin-config
                  key: ASPNETCORE_URLS
            - name: MyDatabase__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: okcoin-secrets
                  key: mongodb-connection-string
            - name: MyDatabase__DatabaseName
              valueFrom:
                configMapKeyRef:
                  name: okcoin-config
                  key: MyDatabase__DatabaseName
            - name: MyDatabase__RedisConnectionString
              valueFrom:
                secretKeyRef:
                  name: okcoin-secrets
                  key: redis-connection-string

---

# Service cho okcoin-api
apiVersion: v1
kind: Service
metadata:
  name: okcoin-api-service
  namespace: minigame
spec:
  selector:
    app: okcoin-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30180
  type: NodePort